version: '3.6'

services:
  # The Cypress testing service
  cypress:
    build:
      context: .
      dockerfile: etc/docker/cypress/Dockerfile
    networks:
      - nextapp-network
    environment:
      - CYPRESS_VIDEO=false
      - CYPRESS_SCREENSHOT_ON_RUN_FAILURE=false
      - DISPLAY
      - TEST_TYPE=$TEST_TYPE
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $PWD/src/website/cypress:/app/cypress
      - $PWD/src/website/.env.local:/app/.env.local
      - $PWD/src/website/.env:/app/.env
      - $PWD/src/website/app:/app/app:ro
      - $PWD/src/website/public:/app/public:ro
      - $PWD/src/website/styles:/app/styles:ro
      - $PWD/src/website/package.json:/app/package.json
      - $PWD/src/website/tsconfig.json:/app/tsconfig.json
      - $PWD/src/website/next.config.js:/app/next.config.js
      - $PWD/src/website/tailwind.config.js:/app/tailwind.config.js
      - $PWD/src/website/postcss.config.js:/app/postcss.config.js
      - $PWD/src/website/yarn.lock:/app/yarn.lock

  # Run the next JS application in dev mode
  dev:
    build:
      context: .
      dockerfile: etc/docker/node/Dockerfile
    networks:
      - nextapp-network
    user: 1000:1000
    working_dir: /app
    ports:
      - 3000:3000
    volumes:
      - $PWD/src/website/node_modules:/app/node_modules
      - $PWD/src/website/.next:/app/.next
      - $PWD/src/website/app:/app/app:ro
      - $PWD/src/website/public:/app/public:ro
      - $PWD/src/website/.env.local:/app/.env.local
      - $PWD/src/website/.env:/app/.env
      - $PWD/src/website/styles:/app/styles:ro
      - $PWD/src/website/package.json:/app/package.json
      - $PWD/src/website/tsconfig.json:/app/tsconfig.json
      - $PWD/src/website/next.config.js:/app/next.config.js
      - $PWD/src/website/tailwind.config.js:/app/tailwind.config.js
      - $PWD/src/website/postcss.config.js:/app/postcss.config.js
      - $PWD/src/website/yarn.lock:/app/yarn.lock
  # One time setup
  setup:
    build:
      context: .
      dockerfile: etc/docker/node/Dockerfile
    user: 1000:1000
    working_dir: /app
    volumes:
      - $PWD/src/website:/app
    entrypoint: /home/node/entrypoint-setup.sh

networks:
  nextapp-network:
